# Use an official Node.js runtime as a parent image
FROM node:22.9.0

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Install Sequelize CLI globally
RUN npm install -g sequelize-cli

# Copy the rest of your application code
COPY . .

# Expose the port the app runs on
EXPOSE 5000

# Command to run migrations and then start the application
CMD ["sh", "-c", "npx sequelize-cli db:migrate && node app.js"]
