# Use a Node.js 22.9.0 image as base
FROM node:22.9.0

# Create and set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the desired port
EXPOSE 5008

# Command to run the application
CMD ["node", "app.js"]
