# Use an official Node.js runtime as a parent image
FROM node:22.9.0

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Clear npm cache and install dependencies
RUN npm cache clean --force
RUN rm -rf node_modules package-lock.json
RUN npm install

# Copy the rest of your application code
COPY . .

# Set environment variables
ENV NODE_ENV=production

# Build the application
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]


# Use an official Node.js runtime as a parent image
# FROM node:22.9.0

# Set the working directory
#WORKDIR /app

# Copy package.json and package-lock.json
#COPY package*.json ./

# Install dependencies
#RUN npm install

# Copy the rest of your application code
#COPY . .

# Expose the port the app runs on
#EXPOSE 3000

# Command to run the application
# CMD ["npm", "run", "dev"]
